name: ci
on:
  push:
    tags: [v*]
env:
  CI: 1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run CI
        run: scripts/ci.sh
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          AZURE_MARKETPLACE_TOKEN: ${{ secrets.AZURE_MARKETPLACE_TOKEN }}
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
